spring.application.name=ss04-ex2-defensive-dto
spring.main.web-application-type=none

spring.datasource.url=jdbc:h2:mem:ss04ex2;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
